import fs from "fs";
import pdfParse from "pdf-parse";
import { openai } from "@workspace/integrations-openai-ai-server";
import type { DocumentMetadata, Finding } from "@workspace/db";
import { logger } from "./logger";

export interface AnalysisResult {
  verdict: "authentic" | "suspicious" | "likely_forged" | "inconclusive";
  confidenceScore: number;
  summary: string;
  findings: Finding[];
  metadata: DocumentMetadata;
}

function normalizeDate(raw: unknown): string | null {
  if (!raw || typeof raw !== "string") return null;
  const m = raw.match(/^D:(\d{4})(\d{2})(\d{2})/);
  if (m) return `${m[1]}-${m[2]}-${m[3]}`;
  return raw.slice(0, 50);
}

export async function extractPdfMetadata(
  buffer: Buffer,
  fileSize: number
): Promise<{ metadata: DocumentMetadata; rawText: string }> {
  let info: Record<string, unknown> = {};
  let numpages: number | null = null;
  let version: string | null = null;
  let rawText = "";

  try {
    const parsed = await pdfParse(buffer);
    info = (parsed.info as Record<string, unknown>) ?? {};
    numpages = parsed.numpages ?? null;
    version = parsed.version ?? null;
    rawText = parsed.text ?? "";
  } catch (err) {
    logger.warn({ err }, "pdf-parse failed; continuing with partial metadata");
  }

  return {
    metadata: {
      author: (info["Author"] as string) || null,
      creator: (info["Creator"] as string) || null,
      producer: (info["Producer"] as string) || null,
      creationDate: normalizeDate(info["CreationDate"]),
      modificationDate: normalizeDate(info["ModDate"]),
      pageCount: numpages,
      fileSize,
      encrypted: false,
      hasDigitalSignature: false,
      pdfVersion: version,
    },
    rawText,
  };
}

function buildHeuristicFindings(
  metadata: DocumentMetadata,
  claimedIdentity: string,
  rawText: string
): Finding[] {
  const findings: Finding[] = [];
  const claimed = claimedIdentity.toLowerCase();

  const creator = (metadata.creator ?? "").toLowerCase();
  const producer = (metadata.producer ?? "").toLowerCase();

  const suspectCreators = ["microsoft word", "libreoffice", "openoffice", "google docs", "wps office", "pages"];
  const suspectProducers = ["microsoft", "libreoffice", "openoffice", "google", "wps", "apple"];

  const claimsBankOrGov = /bank|financial|government|federal|state|court|official|institution|authority|agency/.test(claimed);

  if (claimsBankOrGov) {
    const createdByConsumerSoftware = suspectCreators.some((s) => creator.includes(s));
    const producedByConsumerSoftware = suspectProducers.some((s) => producer.includes(s));
    if (createdByConsumerSoftware || producedByConsumerSoftware) {
      findings.push({
        category: "software",
        severity: "critical",
        title: "Consumer word-processing software detected",
        description:
          `The document's embedded metadata shows it was created using "${metadata.creator || metadata.producer}", ` +
          `which is consumer-grade office software. Legitimate documents from banks, government agencies, and ` +
          `institutions are typically generated by specialized document management systems — not personal word ` +
          `processors. This is a significant red flag for a document claiming to originate from a formal institution.`,
      });
    }
  } else if (creator && suspectCreators.some((s) => creator.includes(s))) {
    findings.push({
      category: "software",
      severity: "medium",
      title: "Document created with personal office software",
      description: `This document was authored in "${metadata.creator}", a personal office application. ` +
        `Depending on the claimed origin, this may or may not be expected.`,
    });
  }

  if (metadata.creationDate && metadata.modificationDate && metadata.creationDate !== metadata.modificationDate) {
    findings.push({
      category: "timestamp",
      severity: "low",
      title: "Document was modified after initial creation",
      description:
        `The embedded creation date (${metadata.creationDate}) differs from the modification date ` +
        `(${metadata.modificationDate}). The document was edited after its initial creation.`,
    });
  }

  const yearMatch = claimedIdentity.match(/\b(19|20)\d{2}\b/);
  if (yearMatch && metadata.creationDate) {
    const claimedYear = parseInt(yearMatch[0]);
    const metaYear = parseInt(metadata.creationDate.slice(0, 4));
    if (Math.abs(claimedYear - metaYear) > 1) {
      findings.push({
        category: "timestamp",
        severity: "high",
        title: "Claimed date conflicts with embedded metadata date",
        description:
          `The submitter claims this document is from ${claimedYear}, but the embedded PDF metadata ` +
          `indicates a creation date of ${metadata.creationDate}. A discrepancy of more than one year ` +
          `between the claimed date and the document's internal timestamps is a significant inconsistency.`,
      });
    }
  }

  if (!metadata.author && claimsBankOrGov) {
    findings.push({
      category: "metadata",
      severity: "medium",
      title: "No author field in metadata",
      description:
        `The document contains no Author field in its embedded metadata. Official institutional documents ` +
        `typically carry author or department information in their properties.`,
    });
  }

  if (metadata.author) {
    const isPersonalName = /^[A-Z][a-z]+ [A-Z][a-z]+$/.test(metadata.author.trim());
    if (isPersonalName && claimsBankOrGov) {
      findings.push({
        category: "metadata",
        severity: "high",
        title: "Personal name found as document author",
        description:
          `The Author metadata field contains what appears to be a personal name ("${metadata.author}") ` +
          `rather than an institution name. Official institutional documents typically list the organization ` +
          `as the author — not an individual's name embedded in PDF metadata.`,
      });
    }
  }

  if (!metadata.producer && !metadata.creator) {
    findings.push({
      category: "metadata",
      severity: "low",
      title: "Missing software metadata fields",
      description:
        `Both the Creator and Producer fields are absent from this PDF's metadata. This can indicate ` +
        `metadata was deliberately stripped, or the document was created by a non-standard tool.`,
    });
  }

  if (rawText) {
    const templatePhrases = ["[insert", "lorem ipsum", "sample text", "placeholder", "your name here"];
    const foundTemplate = templatePhrases.filter((p) => rawText.toLowerCase().includes(p));
    if (foundTemplate.length > 0) {
      findings.push({
        category: "content",
        severity: "critical",
        title: "Template placeholder text detected in document body",
        description:
          `The document text contains template placeholder language: ${foundTemplate.map((p) => `"${p}"`).join(", ")}. ` +
          `This strongly indicates the document was created from a template and not finalized before submission.`,
      });
    }
  }

  return findings;
}

async function runAiAnalysis(
  metadata: DocumentMetadata,
  claimedIdentity: string,
  rawText: string,
  heuristicFindings: Finding[]
): Promise<{ aiFindings: Finding[]; summary: string; verdict: AnalysisResult["verdict"]; confidence: number }> {
  const heuristicSummary = heuristicFindings.length > 0
    ? heuristicFindings.map((f) => `[${f.severity.toUpperCase()}] ${f.category}: ${f.title}`).join("\n")
    : "(none)";

  const prompt = `You are a forensic document examiner with expertise in detecting forged or fabricated documents used in legal proceedings.

CLAIMED IDENTITY: "${claimedIdentity}"

PDF METADATA:
- Creator: ${metadata.creator || "Unknown"}
- Producer: ${metadata.producer || "Unknown"}
- Author: ${metadata.author || "None"}
- Creation date: ${metadata.creationDate || "Unknown"}
- Modification date: ${metadata.modificationDate || "Unknown"}
- Page count: ${metadata.pageCount ?? "Unknown"}
- PDF version: ${metadata.pdfVersion || "Unknown"}

DOCUMENT TEXT (first 3000 chars):
${rawText.slice(0, 3000) || "(No extractable text)"}

RULE-BASED FINDINGS:
${heuristicSummary}

Analyze for signs of fabrication. Consider: metadata vs claimed identity consistency, software fingerprints, content coherence, language/terminology for the claimed institution, date inconsistencies.

Return ONLY valid JSON (no markdown fences):
{
  "verdict": "authentic" | "suspicious" | "likely_forged" | "inconclusive",
  "confidence": <0-100>,
  "summary": "<one professional paragraph suitable for an attorney or judge>",
  "additionalFindings": [
    { "category": "metadata|software|timestamp|content|language|structure", "severity": "info|low|medium|high|critical", "title": "...", "description": "..." }
  ]
}

Verdict: authentic=all signals align; suspicious=moderate red flags; likely_forged=multiple strong indicators; inconclusive=insufficient data.`;

  const response = await openai.chat.completions.create({
    model: "gpt-5.6-terra",
    max_completion_tokens: 2048,
    messages: [{ role: "user", content: prompt }],
  });

  const raw = response.choices[0]?.message?.content ?? "{}";
  let parsed: { verdict?: string; confidence?: number; summary?: string; additionalFindings?: Finding[] } = {};

  try {
    const clean = raw.replace(/^```json\s*/i, "").replace(/```\s*$/i, "").trim();
    parsed = JSON.parse(clean);
  } catch {
    logger.warn({ raw }, "Failed to parse AI response JSON");
  }

  const validVerdicts = ["authentic", "suspicious", "likely_forged", "inconclusive"];
  const verdict = validVerdicts.includes(parsed.verdict ?? "")
    ? (parsed.verdict as AnalysisResult["verdict"])
    : "inconclusive";

  return {
    verdict,
    confidence: typeof parsed.confidence === "number" ? Math.min(100, Math.max(0, parsed.confidence)) : 50,
    summary: parsed.summary ?? "Analysis completed. See individual findings for details.",
    aiFindings: Array.isArray(parsed.additionalFindings) ? parsed.additionalFindings : [],
  };
}

export async function analyzeDocument(
  filePath: string,
  fileName: string,
  fileSize: number,
  claimedIdentity: string
): Promise<AnalysisResult> {
  const buffer = fs.readFileSync(filePath);
  const { metadata, rawText } = await extractPdfMetadata(buffer, fileSize);
  const heuristicFindings = buildHeuristicFindings(metadata, claimedIdentity, rawText);
  const { verdict, confidence, summary, aiFindings } = await runAiAnalysis(
    metadata, claimedIdentity, rawText, heuristicFindings
  );

  const allFindings: Finding[] = [...heuristicFindings];
  for (const af of aiFindings) {
    const alreadyPresent = allFindings.some((f) => f.title.toLowerCase() === af.title?.toLowerCase());
    if (!alreadyPresent && af.title && af.description) {
      allFindings.push({
        category: af.category ?? "metadata",
        severity: (["info", "low", "medium", "high", "critical"].includes(af.severity)
          ? af.severity : "low") as Finding["severity"],
        title: af.title,
        description: af.description,
      });
    }
  }

  return { verdict, confidenceScore: confidence, summary, findings: allFindings, metadata };
}
